server:
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30

dubbo:
  consumer:
    check: false
  registry:
    address: zookeeper://106.52.162.92:2181
  application:
    name: nnxi-auth-consumer
