server:
  name: nnxi-auth-service
  port: 8092
  tomcat:
    max-threads: 1000
    min-spare-threads: 30

spring:
  application:
    name: nnxi-auth-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://106.52.162.92:3306/auth_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC    #mysql8
    username: root
    password: nnx13726338256
    name: auth_db
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      pool-prepared-statements: true
      max-open-prepared-statements: 20
#    filters: stat,wall,log4j
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.nnxi.model  #扫描实体类,配置xml的别名
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除配置
      logic-not-delete-value: 1 #删除前
      logic-delete-value: 0  #删除后

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug


dubbo:
  registry:
    address: zookeeper://106.52.162.92:2181
    group: nnxi-auth
    version: 0.1.0
    timeout: 12000
  application:
    name: nnxi-auth-provider
