server:
  port: 8092
  tomcat:
    max-threads: 1000
    min-spare-threads: 30



spring:
  application:
    name: nnxi-auth-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://106.52.162.92:3306/auth_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC    #mysql8
    username: root
    password: nnx13726338256
    name: auth_db
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-wait-millis: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      pool-prepared-statements: true
      max-open-prepared-statements: 20

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
    com.nnix.mapper: debug


dubbo:
  registry:
    address: zookeeper://106.52.162.92:2181
  application:
    name: nnxi-auth-provider
