server:
  port: 8080
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /order
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*


#nnxi专用配置
nnxi :
  path :
    #文件上传根目录 设置
    upload: upFiles
    #webapp文件路径
    webapp: webapp

dubbo:
  consumer:
    check: false
    timeout: 5000
  registry:
    address: zookeeper://106.52.162.92:2181
  application:
    name: nnxi-order-consumer

spring:
  resources:
    static-locations: classpath:/static/,classpath:/public/
